# Linear queue for the main branch.
queue_rules:
  - name: main
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body | trim }}
    queue_conditions:
      - base=master
      - or:
          - check-pending=integration-test-result
          - check-success=integration-test-result
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
      # Require integration tests before merging only
      - or:
          - label=bypass:integration
          - check-success=integration-test-result

pull_request_rules:
  - name: merge to master
    conditions:
      - base=master
      - label=automerge:no-update
      - or:
          - '#commits-behind=0'
          - label=bypass:linear-history
    actions:
      queue:
        name: main
        merge_method: merge
  - name: rebase updates then merge to master
    conditions:
      - base=master
      - label=automerge:rebase
    actions:
      queue:
        name: main
        merge_method: merge
        update_method: rebase
  - name: squash to master
    conditions:
      - base=master
      - label=automerge:squash
    actions:
      queue:
        name: main
        merge_method: squash
